# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPHTechIOSAppTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ReachabilitySwift'

  # Pods for SPHTechIOSAppTest

  target 'SPHTechIOSAppTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SPHTechIOSAppTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
